spring:
  data:
    mongodb:
      database: shop
      authentication-database: admin
      username: rootuser
      password: rootpass
      port: 27017
      host: localhost
      auto-index-creation: true